-- AlterTable
ALTER TABLE "GalleryMediaAsset" ADD COLUMN     "cropScale" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "cropX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cropY" DOUBLE PRECISION NOT NULL DEFAULT 0;
