import type { PublicLocale } from "./i18n";

export type BookingServiceDetailCopy = {
  tag: string;
  title: string;
  priceRange: string;
  sections: Array<{ title: string; items: string[] }>;
};

export const bookingPageCopy = {
  de: {
    eyebrow: "Termin buchen",
    title: "Deine Anfrage für JC Detailing",
    description: "Schick uns die wichtigsten Angaben zu deinem Fahrzeug. Wir prüfen die Anfrage und melden uns mit einer Terminbestätigung oder einem passenden Vorschlag.",
    sectionEyebrow: "Anfrage",
    sectionTitle: "Fahrzeug, Leistung und Wunschdatum.",
    sectionDescription: "Die Anfrage ist noch keine verbindliche Buchung. Du erhältst zuerst eine Bestätigung per E-Mail, sobald der Termin geprüft wurde.",
  },
  en: {
    eyebrow: "Book an appointment",
    title: "Your request for JC Detailing",
    description: "Send us the key details about your vehicle. We will review your request and reply with a confirmation or a suitable alternative.",
    sectionEyebrow: "Request",
    sectionTitle: "Vehicle, service and preferred date.",
    sectionDescription: "Your request is not a confirmed booking yet. You will receive an email confirmation once the appointment has been reviewed.",
  },
  fr: {
    eyebrow: "Prendre rendez-vous",
    title: "Votre demande pour JC Detailing",
    description: "Envoyez-nous les informations principales sur votre véhicule. Nous examinerons votre demande et vous répondrons avec une confirmation ou une autre proposition.",
    sectionEyebrow: "Demande",
    sectionTitle: "Véhicule, service et date souhaitée.",
    sectionDescription: "Votre demande ne constitue pas encore une réservation confirmée. Vous recevrez une confirmation par e-mail après vérification du rendez-vous.",
  },
  it: {
    eyebrow: "Prenota un appuntamento",
    title: "La tua richiesta per JC Detailing",
    description: "Inviaci le informazioni principali sul veicolo. Esamineremo la richiesta e risponderemo con una conferma o una proposta alternativa.",
    sectionEyebrow: "Richiesta",
    sectionTitle: "Veicolo, servizio e data desiderata.",
    sectionDescription: "La richiesta non è ancora una prenotazione confermata. Riceverai una conferma via e-mail dopo la verifica dell'appuntamento.",
  },
} as const satisfies Record<PublicLocale, object>;

export const bookingFormCopy = {
  de: {
    steps: ["Service", "Grösse", "Extras", "Termin", "Details"],
    selectServices: "Leistungen auswählen",
    selectServicesHelp: "Du kannst eine oder mehrere Leistungen auswählen.",
    addOn: "Zusatzleistung",
    addOns: "Zusatzleistungen",
    viewDetails: "Details ansehen",
    from: "Ab",
    add: "Hinzufügen",
    remove: "Entfernen",
    detailsPending: "Details werden nachgetragen.",
    moreServices: "Mehr Services",
    fewerServices: "Weniger Services",
    selectVehicle: "Fahrzeuggrösse auswählen",
    vehicleCategory: "Fahrzeugkategorie",
    included: "inkl.",
    extras: "Zusatzleistungen hinzufügen (optional)",
    extrasHelp: "Wähle nur die Zusatzleistungen, die du wirklich brauchst.",
    noExtras: "Für die ausgewählten Leistungen sind keine Zusatzleistungen verfügbar. Du kannst direkt weitergehen.",
    selectDate: "Datum und Uhrzeit auswählen",
    weekdays: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
    availableAt: "Verfügbare Uhrzeiten am",
    forAbout: "für ca.",
    checkingTimes: "Zeiten werden geprüft...",
    fields: { name: "Name", email: "E-Mail", phone: "Telefon", address: "Adresse", vehicle: "Fahrzeugmodell", promoCode: "Promo-Code (optional)", message: "Nachricht (optional)" },
    vehiclePlaceholder: "z. B. BMW X5, Audi A4",
    messagePlaceholder: "Erzähl uns kurz, was gemacht werden soll oder worauf wir achten sollen.",
    estimatedTotal: "Geschätzter Gesamtpreis",
    duration: "Dauer",
    back: "Zurück",
    next: "Weiter",
    sending: "Wird gesendet",
    send: "Anfrage senden",
    chooseServiceError: "Bitte wähle mindestens eine Leistung aus.",
    chooseDateError: "Bitte wähle ein Datum und eine Uhrzeit aus.",
    requestError: "Die Anfrage konnte nicht gesendet werden.",
    none: "Keine",
    confirmationEyebrow: "Terminanfrage erhalten",
    confirmationTitle: "Danke für deine Anfrage",
    confirmationText: "Deine Terminanfrage wurde erfolgreich gesendet. Du erhältst eine Eingangsbestätigung per E-Mail. Der Termin ist noch nicht bestätigt. Sobald JC Detailing den Termin geprüft hat, erhältst du eine separate Terminbestätigung.",
    confirmationNotice: "Bitte prüfe auch deinen Spam-Ordner, falls du die E-Mail nicht direkt findest.",
    summary: { date: "Datum", time: "Uhrzeit", services: "Leistung", vehicle: "Fahrzeug", category: "Fahrzeuggrösse", extras: "Zusatzleistungen", duration: "Dauer", price: "Geschätzter Preis", discount: "Promo-Rabatt", email: "E-Mail", phone: "Telefon", address: "Adresse" },
    home: "Zur Startseite",
    whatsapp: "WhatsApp öffnen",
    closeDetails: "Details schliessen",
    service: "Leistung",
    includedServices: "Enthaltene Leistungen",
    bookingType: "Verfügbare Buchungsart",
    studio: "Im Studio",
    studioText: "Termin am Standort von JC Detailing in Wauwil.",
    select: "Auswählen",
  },
  en: {
    steps: ["Service", "Size", "Extras", "Appointment", "Details"],
    selectServices: "Select services",
    selectServicesHelp: "You can select one or more services.",
    addOn: "add-on",
    addOns: "add-ons",
    viewDetails: "View details",
    from: "From",
    add: "Add",
    remove: "Remove",
    detailsPending: "Details will be added shortly.",
    moreServices: "More services",
    fewerServices: "Fewer services",
    selectVehicle: "Select vehicle size",
    vehicleCategory: "Vehicle category",
    included: "included",
    extras: "Add extras (optional)",
    extrasHelp: "Select only the extras you need.",
    noExtras: "No extras are available for the selected services. You can continue to the next step.",
    selectDate: "Select date and time",
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    availableAt: "Available times on",
    forAbout: "for about",
    checkingTimes: "Checking available times...",
    fields: { name: "Name", email: "Email", phone: "Phone", address: "Address", vehicle: "Vehicle model", promoCode: "Promo code (optional)", message: "Message (optional)" },
    vehiclePlaceholder: "e.g. BMW X5, Audi A4",
    messagePlaceholder: "Tell us briefly what you would like done or anything we should know.",
    estimatedTotal: "Estimated total",
    duration: "Duration",
    back: "Back",
    next: "Next",
    sending: "Sending",
    send: "Send request",
    chooseServiceError: "Please select at least one service.",
    chooseDateError: "Please select a date and time.",
    requestError: "Your request could not be sent.",
    none: "None",
    confirmationEyebrow: "Appointment request received",
    confirmationTitle: "Thank you for your request",
    confirmationText: "Your appointment request was sent successfully. You will receive an email acknowledging your request. The appointment is not confirmed yet. JC Detailing will send a separate confirmation after reviewing it.",
    confirmationNotice: "Please also check your spam folder if the email does not arrive immediately.",
    summary: { date: "Date", time: "Time", services: "Service", vehicle: "Vehicle", category: "Vehicle size", extras: "Extras", duration: "Duration", price: "Estimated price", discount: "Promo discount", email: "Email", phone: "Phone", address: "Address" },
    home: "Back to home",
    whatsapp: "Open WhatsApp",
    closeDetails: "Close details",
    service: "Service",
    includedServices: "Included services",
    bookingType: "Available booking method",
    studio: "At the studio",
    studioText: "Appointment at the JC Detailing studio in Wauwil.",
    select: "Select",
  },
  fr: {
    steps: ["Service", "Taille", "Options", "Rendez-vous", "Coordonnées"],
    selectServices: "Choisir les services",
    selectServicesHelp: "Vous pouvez sélectionner un ou plusieurs services.",
    addOn: "option",
    addOns: "options",
    viewDetails: "Voir les détails",
    from: "Dès",
    add: "Ajouter",
    remove: "Retirer",
    detailsPending: "Les détails seront ajoutés prochainement.",
    moreServices: "Plus de services",
    fewerServices: "Moins de services",
    selectVehicle: "Choisir la taille du véhicule",
    vehicleCategory: "Catégorie de véhicule",
    included: "inclus",
    extras: "Ajouter des options (facultatif)",
    extrasHelp: "Sélectionnez uniquement les options dont vous avez besoin.",
    noExtras: "Aucune option n'est disponible pour les services sélectionnés. Vous pouvez continuer.",
    selectDate: "Choisir la date et l'heure",
    weekdays: ["Lu", "Ma", "Me", "Je", "Ve", "Sa", "Di"],
    availableAt: "Horaires disponibles le",
    forAbout: "pour environ",
    checkingTimes: "Vérification des horaires...",
    fields: { name: "Nom", email: "E-mail", phone: "Téléphone", address: "Adresse", vehicle: "Modèle du véhicule", promoCode: "Code promo (facultatif)", message: "Message (facultatif)" },
    vehiclePlaceholder: "p. ex. BMW X5, Audi A4",
    messagePlaceholder: "Décrivez brièvement le travail souhaité ou les points auxquels nous devons faire attention.",
    estimatedTotal: "Total estimé",
    duration: "Durée",
    back: "Retour",
    next: "Suivant",
    sending: "Envoi en cours",
    send: "Envoyer la demande",
    chooseServiceError: "Veuillez sélectionner au moins un service.",
    chooseDateError: "Veuillez sélectionner une date et une heure.",
    requestError: "Votre demande n'a pas pu être envoyée.",
    none: "Aucune",
    confirmationEyebrow: "Demande de rendez-vous reçue",
    confirmationTitle: "Merci pour votre demande",
    confirmationText: "Votre demande de rendez-vous a bien été envoyée. Vous recevrez un accusé de réception par e-mail. Le rendez-vous n'est pas encore confirmé. JC Detailing vous enverra une confirmation séparée après vérification.",
    confirmationNotice: "Vérifiez également votre dossier de courriers indésirables si l'e-mail n'arrive pas immédiatement.",
    summary: { date: "Date", time: "Heure", services: "Service", vehicle: "Véhicule", category: "Taille du véhicule", extras: "Options", duration: "Durée", price: "Prix estimé", discount: "Remise promo", email: "E-mail", phone: "Téléphone", address: "Adresse" },
    home: "Retour à l'accueil",
    whatsapp: "Ouvrir WhatsApp",
    closeDetails: "Fermer les détails",
    service: "Service",
    includedServices: "Services inclus",
    bookingType: "Mode de réservation disponible",
    studio: "Au studio",
    studioText: "Rendez-vous au studio JC Detailing à Wauwil.",
    select: "Sélectionner",
  },
  it: {
    steps: ["Servizio", "Dimensione", "Extra", "Appuntamento", "Dettagli"],
    selectServices: "Seleziona i servizi",
    selectServicesHelp: "Puoi selezionare uno o più servizi.",
    addOn: "extra",
    addOns: "extra",
    viewDetails: "Vedi dettagli",
    from: "Da",
    add: "Aggiungi",
    remove: "Rimuovi",
    detailsPending: "I dettagli saranno aggiunti a breve.",
    moreServices: "Altri servizi",
    fewerServices: "Meno servizi",
    selectVehicle: "Seleziona la dimensione del veicolo",
    vehicleCategory: "Categoria del veicolo",
    included: "incluso",
    extras: "Aggiungi extra (facoltativo)",
    extrasHelp: "Seleziona solo gli extra di cui hai bisogno.",
    noExtras: "Non sono disponibili extra per i servizi selezionati. Puoi continuare.",
    selectDate: "Seleziona data e ora",
    weekdays: ["Lu", "Ma", "Me", "Gi", "Ve", "Sa", "Do"],
    availableAt: "Orari disponibili il",
    forAbout: "per circa",
    checkingTimes: "Verifica degli orari...",
    fields: { name: "Nome", email: "E-mail", phone: "Telefono", address: "Indirizzo", vehicle: "Modello del veicolo", promoCode: "Codice promo (facoltativo)", message: "Messaggio (facoltativo)" },
    vehiclePlaceholder: "ad es. BMW X5, Audi A4",
    messagePlaceholder: "Descrivi brevemente il lavoro desiderato o eventuali aspetti a cui prestare attenzione.",
    estimatedTotal: "Totale stimato",
    duration: "Durata",
    back: "Indietro",
    next: "Avanti",
    sending: "Invio in corso",
    send: "Invia richiesta",
    chooseServiceError: "Seleziona almeno un servizio.",
    chooseDateError: "Seleziona una data e un orario.",
    requestError: "Non è stato possibile inviare la richiesta.",
    none: "Nessuno",
    confirmationEyebrow: "Richiesta di appuntamento ricevuta",
    confirmationTitle: "Grazie per la tua richiesta",
    confirmationText: "La richiesta di appuntamento è stata inviata. Riceverai un'e-mail di conferma della ricezione. L'appuntamento non è ancora confermato. JC Detailing invierà una conferma separata dopo la verifica.",
    confirmationNotice: "Controlla anche la cartella spam se l'e-mail non arriva subito.",
    summary: { date: "Data", time: "Ora", services: "Servizio", vehicle: "Veicolo", category: "Dimensione del veicolo", extras: "Extra", duration: "Durata", price: "Prezzo stimato", discount: "Sconto promo", email: "E-mail", phone: "Telefono", address: "Indirizzo" },
    home: "Torna alla home",
    whatsapp: "Apri WhatsApp",
    closeDetails: "Chiudi dettagli",
    service: "Servizio",
    includedServices: "Servizi inclusi",
    bookingType: "Modalità di prenotazione disponibile",
    studio: "In studio",
    studioText: "Appuntamento presso lo studio JC Detailing a Wauwil.",
    select: "Seleziona",
  },
} as const satisfies Record<PublicLocale, object>;

export const bookingServiceNames: Record<PublicLocale, Record<string, string>> = {
  de: {},
  en: {
    "Komplett Innenreinigung": "Complete interior detailing",
    "Komplett Aussenreinigung": "Complete exterior detailing",
    "Pflegeerhaltung Innenreinigung": "Interior maintenance care",
    "Pflegeerhaltung Aussenreinigung": "Exterior maintenance care",
    "Polish Paket (1-Step)": "Polish package (1-step)",
    "Polish Paket (2-Step)": "Polish package (2-step)",
    "Keramik Versiegelung": "Ceramic coating",
    "Komplette Premium Paket": "Complete premium package",
  },
  fr: {
    "Komplett Innenreinigung": "Nettoyage intérieur complet",
    "Komplett Aussenreinigung": "Nettoyage extérieur complet",
    "Pflegeerhaltung Innenreinigung": "Entretien intérieur",
    "Pflegeerhaltung Aussenreinigung": "Entretien extérieur",
    "Polish Paket (1-Step)": "Polissage 1 étape",
    "Polish Paket (2-Step)": "Polissage 2 étapes",
    "Keramik Versiegelung": "Protection céramique",
    "Komplette Premium Paket": "Forfait premium complet",
  },
  it: {
    "Komplett Innenreinigung": "Pulizia interna completa",
    "Komplett Aussenreinigung": "Pulizia esterna completa",
    "Pflegeerhaltung Innenreinigung": "Manutenzione interna",
    "Pflegeerhaltung Aussenreinigung": "Manutenzione esterna",
    "Polish Paket (1-Step)": "Pacchetto lucidatura 1-step",
    "Polish Paket (2-Step)": "Pacchetto lucidatura 2-step",
    "Keramik Versiegelung": "Rivestimento ceramico",
    "Komplette Premium Paket": "Pacchetto premium completo",
  },
};

export const bookingAddOnCopy: Record<PublicLocale, Record<string, { name: string; description: string }>> = {
  de: {
    Tierhaarentfernung: { name: "Tierhaarentfernung", description: "Effektive Entfernung hartnäckiger Tierhaare." },
    "Sitze Tiefenreinigung": { name: "Sitze Tiefenreinigung", description: "Intensive Polsterreinigung für hygienische Sitze." },
    "Fussmatten intensiv": { name: "Fussmatten intensiv", description: "Tiefenreinigung für saubere Fussmatten." },
    "Kofferraum Deep Clean": { name: "Kofferraum Deep Clean", description: "Gründliche Reinigung des Kofferraums." },
  },
  en: {
    Tierhaarentfernung: { name: "Pet-hair removal", description: "Effective removal of stubborn pet hair." },
    "Sitze Tiefenreinigung": { name: "Deep seat cleaning", description: "Intensive upholstery cleaning for hygienic seats." },
    "Fussmatten intensiv": { name: "Intensive floor-mat cleaning", description: "Deep cleaning for fresh floor mats." },
    "Kofferraum Deep Clean": { name: "Boot deep clean", description: "Thorough cleaning of the boot." },
  },
  fr: {
    Tierhaarentfernung: { name: "Retrait des poils d'animaux", description: "Élimination efficace des poils tenaces." },
    "Sitze Tiefenreinigung": { name: "Nettoyage profond des sièges", description: "Nettoyage intensif des tissus pour des sièges hygiéniques." },
    "Fussmatten intensiv": { name: "Nettoyage intensif des tapis", description: "Nettoyage en profondeur des tapis de sol." },
    "Kofferraum Deep Clean": { name: "Nettoyage profond du coffre", description: "Nettoyage complet du coffre." },
  },
  it: {
    Tierhaarentfernung: { name: "Rimozione peli di animali", description: "Rimozione efficace dei peli più ostinati." },
    "Sitze Tiefenreinigung": { name: "Pulizia profonda dei sedili", description: "Pulizia intensiva dei tessuti per sedili igienizzati." },
    "Fussmatten intensiv": { name: "Pulizia intensiva dei tappetini", description: "Pulizia profonda dei tappetini." },
    "Kofferraum Deep Clean": { name: "Pulizia profonda del bagagliaio", description: "Pulizia completa del bagagliaio." },
  },
};

export const bookingVehicleCopy: Record<PublicLocale, Record<string, { title: string; description: string }>> = {
  de: {
    "City Car": { title: "City Car", description: "Kleine Fahrzeuge (Mini, Fiat 500)" },
    Sedan: { title: "Limousine", description: "Standardfahrzeuge (Audi A4, Mercedes C-Klasse)" },
    "Sports Car": { title: "Sportwagen", description: "Sportliche Fahrzeuge (Porsche, Ferrari)" },
    SUV: { title: "SUV", description: "Grössere Fahrzeuge (Peugeot 5008, Range Rover)" },
    Van: { title: "Van", description: "Minivans und Transporter" },
  },
  en: {
    "City Car": { title: "City car", description: "Small vehicles (Mini, Fiat 500)" },
    Sedan: { title: "Sedan", description: "Standard cars (Audi A4, Mercedes C-Class)" },
    "Sports Car": { title: "Sports car", description: "Sports cars (Porsche, Ferrari)" },
    SUV: { title: "SUV", description: "Larger vehicles (Peugeot 5008, Range Rover)" },
    Van: { title: "Van", description: "Minivans and vans" },
  },
  fr: {
    "City Car": { title: "Citadine", description: "Petits véhicules (Mini, Fiat 500)" },
    Sedan: { title: "Berline", description: "Véhicules standards (Audi A4, Mercedes Classe C)" },
    "Sports Car": { title: "Voiture de sport", description: "Voitures sportives (Porsche, Ferrari)" },
    SUV: { title: "SUV", description: "Grands véhicules (Peugeot 5008, Range Rover)" },
    Van: { title: "Van", description: "Monospaces et utilitaires" },
  },
  it: {
    "City Car": { title: "City car", description: "Veicoli piccoli (Mini, Fiat 500)" },
    Sedan: { title: "Berlina", description: "Auto standard (Audi A4, Mercedes Classe C)" },
    "Sports Car": { title: "Auto sportiva", description: "Auto sportive (Porsche, Ferrari)" },
    SUV: { title: "SUV", description: "Veicoli grandi (Peugeot 5008, Range Rover)" },
    Van: { title: "Van", description: "Monovolume e furgoni" },
  },
};

const nonGermanDetails: Record<Exclude<PublicLocale, "de">, Record<string, BookingServiceDetailCopy>> = {
  en: {
    "Komplett Innenreinigung": detail("Interior detailing", "Complete interior detailing", "CHF 209.00 - CHF 309.00", ["Vacuuming of the complete interior and boot", "Cleaning and protective care of plastic surfaces", "Deep seat cleaning with shampoo and stain treatment", "Deep carpet cleaning and streak-free interior windows", "Steam cleaning for hygienic details", "Careful care of leather and Alcantara"]),
    "Komplett Aussenreinigung": detail("Exterior detailing", "Complete exterior detailing", "CHF 109.00 - CHF 149.00", ["Snow-foam pre-wash and careful hand wash", "Gentle drying of the complete vehicle", "Intensive wheel and brake-dust cleaning", "Insect removal from the front and mirrors", "Cleaning of door shuts, windows, tyres and fine details"]),
    "Pflegeerhaltung Innenreinigung": maintenanceDetail("Interior maintenance", "Interior maintenance care", "CHF 129.00 - CHF 199.00", ["Vacuuming of the cabin and boot", "Dashboard and centre-console cleaning", "Cleaning of plastics, door shuts and door panels"]),
    "Pflegeerhaltung Aussenreinigung": maintenanceDetail("Exterior maintenance", "Exterior maintenance care", "CHF 69.00 - CHF 109.00", ["Snow-foam pre-wash", "Hand wash and gentle drying", "Wheel cleaning and insect removal"]),
    "Polish Paket (1-Step)": polishDetail("Paint correction", "Polish package (1-step)", "CHF 399.00 - CHF 549.00", ["Paint wash, cleaning and degreasing", "One-step polish for gloss and light defect removal", "Reduction of light swirl marks", "High-gloss finish"]),
    "Polish Paket (2-Step)": polishDetail("Paint correction", "Polish package (2-step)", "CHF 599.00 - CHF 769.00", ["Intensive wash and paint preparation", "Two-step cut and finish polish", "Significant reduction of scratches and swirl marks", "Deep-gloss finish"]),
    "Keramik Versiegelung": detail("Ceramic coating", "Ceramic coating", "CHF 1090.00 - CHF 1690.00", ["Intensive wash and paint preparation", "Polishing for a clean foundation", "Degreasing and professional preparation", "Ceramic coating, curing and final inspection"]),
    "Komplette Premium Paket": detail("Package", "Complete premium package", "CHF 299.00 - CHF 349.00", ["Detailed interior vacuuming, deep cleaning and surface care", "Seat, carpet, leather and Alcantara care", "Careful hand wash and wheel cleaning", "Paint cleaning, gloss finish and spray protection", "Tyre and exterior-plastic care"]),
  },
  fr: {
    "Komplett Innenreinigung": detail("Nettoyage intérieur", "Nettoyage intérieur complet", "CHF 209.00 - CHF 309.00", ["Aspiration complète de l'habitacle et du coffre", "Nettoyage et protection des surfaces en plastique", "Nettoyage profond des sièges avec shampoing et traitement des taches", "Nettoyage profond des tapis et vitres intérieures sans traces", "Nettoyage vapeur hygiénique", "Entretien du cuir et de l'Alcantara"]),
    "Komplett Aussenreinigung": detail("Nettoyage extérieur", "Nettoyage extérieur complet", "CHF 109.00 - CHF 149.00", ["Prélavage Snow Foam et lavage à la main", "Séchage délicat du véhicule", "Nettoyage intensif des jantes et de la poussière de frein", "Retrait des insectes à l'avant et sur les rétroviseurs", "Nettoyage des seuils, vitres, pneus et détails"]),
    "Pflegeerhaltung Innenreinigung": maintenanceDetail("Entretien intérieur", "Entretien intérieur", "CHF 129.00 - CHF 199.00", ["Aspiration de l'habitacle et du coffre", "Nettoyage du tableau de bord et de la console centrale", "Nettoyage des plastiques, seuils et panneaux de porte"]),
    "Pflegeerhaltung Aussenreinigung": maintenanceDetail("Entretien extérieur", "Entretien extérieur", "CHF 69.00 - CHF 109.00", ["Prélavage Snow Foam", "Lavage à la main et séchage délicat", "Nettoyage des jantes et retrait des insectes"]),
    "Polish Paket (1-Step)": polishDetail("Correction de peinture", "Polissage 1 étape", "CHF 399.00 - CHF 549.00", ["Lavage, nettoyage et dégraissage de la peinture", "Polissage en une étape pour la brillance et les défauts légers", "Réduction des micro-rayures légères", "Finition brillante"]),
    "Polish Paket (2-Step)": polishDetail("Correction de peinture", "Polissage 2 étapes", "CHF 599.00 - CHF 769.00", ["Lavage intensif et préparation de la peinture", "Polissage en deux étapes: correction et finition", "Réduction importante des rayures et micro-rayures", "Finition brillante en profondeur"]),
    "Keramik Versiegelung": detail("Protection céramique", "Protection céramique", "CHF 1090.00 - CHF 1690.00", ["Lavage intensif et préparation de la peinture", "Polissage pour une base parfaite", "Dégraissage et préparation professionnelle", "Protection céramique, durcissement et contrôle final"]),
    "Komplette Premium Paket": detail("Forfait", "Forfait premium complet", "CHF 299.00 - CHF 349.00", ["Aspiration, nettoyage profond et entretien de l'habitacle", "Entretien des sièges, tapis, cuirs et Alcantara", "Lavage à la main et nettoyage des jantes", "Nettoyage de la peinture, finition brillante et protection", "Entretien des pneus et plastiques extérieurs"]),
  },
  it: {
    "Komplett Innenreinigung": detail("Pulizia interna", "Pulizia interna completa", "CHF 209.00 - CHF 309.00", ["Aspirazione completa dell'abitacolo e del bagagliaio", "Pulizia e protezione delle superfici in plastica", "Pulizia profonda dei sedili con shampoo e trattamento macchie", "Pulizia profonda dei tappeti e vetri interni senza aloni", "Pulizia a vapore igienizzante", "Cura di pelle e Alcantara"]),
    "Komplett Aussenreinigung": detail("Pulizia esterna", "Pulizia esterna completa", "CHF 109.00 - CHF 149.00", ["Prelavaggio Snow Foam e lavaggio a mano", "Asciugatura delicata del veicolo", "Pulizia intensiva dei cerchi e della polvere dei freni", "Rimozione insetti da frontale e specchietti", "Pulizia di battute, vetri, pneumatici e dettagli"]),
    "Pflegeerhaltung Innenreinigung": maintenanceDetail("Manutenzione interna", "Manutenzione interna", "CHF 129.00 - CHF 199.00", ["Aspirazione di abitacolo e bagagliaio", "Pulizia di cruscotto e console centrale", "Pulizia di plastiche, battute e pannelli porta"]),
    "Pflegeerhaltung Aussenreinigung": maintenanceDetail("Manutenzione esterna", "Manutenzione esterna", "CHF 69.00 - CHF 109.00", ["Prelavaggio Snow Foam", "Lavaggio a mano e asciugatura delicata", "Pulizia cerchi e rimozione insetti"]),
    "Polish Paket (1-Step)": polishDetail("Correzione vernice", "Pacchetto lucidatura 1-step", "CHF 399.00 - CHF 549.00", ["Lavaggio, pulizia e sgrassaggio della vernice", "Lucidatura a uno step per brillantezza e difetti leggeri", "Riduzione dei segni circolari leggeri", "Finitura ad alta brillantezza"]),
    "Polish Paket (2-Step)": polishDetail("Correzione vernice", "Pacchetto lucidatura 2-step", "CHF 599.00 - CHF 769.00", ["Lavaggio intensivo e preparazione della vernice", "Lucidatura in due step: taglio e finitura", "Riduzione significativa di graffi e segni circolari", "Finitura profonda e brillante"]),
    "Keramik Versiegelung": detail("Rivestimento ceramico", "Rivestimento ceramico", "CHF 1090.00 - CHF 1690.00", ["Lavaggio intensivo e preparazione della vernice", "Lucidatura per una base perfetta", "Sgrassaggio e preparazione professionale", "Rivestimento ceramico, indurimento e controllo finale"]),
    "Komplette Premium Paket": detail("Pacchetto", "Pacchetto premium completo", "CHF 299.00 - CHF 349.00", ["Aspirazione, pulizia profonda e cura dell'abitacolo", "Cura di sedili, tappeti, pelle e Alcantara", "Lavaggio a mano e pulizia dei cerchi", "Pulizia vernice, finitura lucida e protezione spray", "Cura di pneumatici e plastiche esterne"]),
  },
};

export function getBookingServiceDetail(locale: PublicLocale, name: string, fallback?: BookingServiceDetailCopy) {
  if (locale === "de") return fallback;

  const value = nonGermanDetails[locale][name];
  if (!value) return fallback;

  const sectionTitles = {
    en: { Services: "Services", Requirement: "Requirement", Important: "Important" },
    fr: { Services: "Prestations", Requirement: "Condition", Important: "Remarque importante" },
    it: { Services: "Servizi", Requirement: "Requisito", Important: "Nota importante" },
  }[locale];
  const genericItems = {
    en: {
      requirement: "The vehicle was previously detailed by JC Detailing or is already in well-maintained condition.",
      important: "The final scope and price depend on the condition of the paint and are confirmed after an inspection.",
    },
    fr: {
      requirement: "Le véhicule a déjà été préparé par JC Detailing ou se trouve dans un état bien entretenu.",
      important: "L'étendue finale et le prix dépendent de l'état de la peinture et sont confirmés après inspection.",
    },
    it: {
      requirement: "Il veicolo è già stato trattato da JC Detailing oppure si trova in buone condizioni.",
      important: "L'intervento finale e il prezzo dipendono dalle condizioni della vernice e vengono confermati dopo un controllo.",
    },
  }[locale];

  return {
    ...value,
    sections: value.sections.map((section) => ({
      ...section,
      title: sectionTitles[section.title as keyof typeof sectionTitles] ?? section.title,
      items: section.items.map((item) => {
        if (item.startsWith("The vehicle was previously")) return genericItems.requirement;
        if (item.startsWith("The final scope and price")) return genericItems.important;
        return item;
      }),
    })),
  };
}

function detail(tag: string, title: string, priceRange: string, items: string[]): BookingServiceDetailCopy {
  return { tag, title, priceRange, sections: [{ title: "Services", items }] };
}

function maintenanceDetail(tag: string, title: string, priceRange: string, items: string[]): BookingServiceDetailCopy {
  return {
    tag,
    title,
    priceRange,
    sections: [
      { title: "Requirement", items: ["The vehicle was previously detailed by JC Detailing or is already in well-maintained condition."] },
      { title: "Services", items },
    ],
  };
}

function polishDetail(tag: string, title: string, priceRange: string, items: string[]): BookingServiceDetailCopy {
  return {
    tag,
    title,
    priceRange,
    sections: [
      { title: "Services", items },
      { title: "Important", items: ["The final scope and price depend on the condition of the paint and are confirmed after an inspection."] },
    ],
  };
}
